language: c
compiler: gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Ysin0s3j16SENbMtvulpD9vB1YwjQdGkLp5F9RRQCC0t7wxRPZX7yItSxvYBCRFE7yikuqFXq9792bcImQvrcH0CIalGsfjC8We3B2zCS4rxIVbNyc1kW3QaCoVjXSqSEnyjUr4ca+HtbwVXV3o40rodh7ACnqBMNq3MlyAkmAU="

addons:
  coverity_scan:
    project:
      name: "1100101/Automatic"
      description: "Build submitted via Travis CI"
    notification_email: 1100101@gmail.com
    build_command_prepend: "./autogen.sh; ./configure; make clean"
    build_command: "make"
    branch_pattern: coverity_scan

# Change this to your needs
script: ./autogen.sh && ./configure && make
